#项目服务器配置
#spring:
#  datasource:
#    master:
#      jdbc-url: jdbc:mysql://localhost:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#      username: root
#      password: root
#      initialSize: 1
#      minIdle: 5
#      maxActive: 100
#      maxWait: 60000
#      testWhileIdle: true
#      testOnReturn: false
#      testOnBorrow: false
#      validationQuery: SELECT 1
#      removeAbandoned: true
#      removeAbandonedTimeout: 1800
#      logAbandoned: true
#      filters: mergeStat
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 25200000
#      type: com.zaxxer.hikari.HikariDataSource
#    other:
#      jdbc-url: jdbc:sqlserver://192.168.1.105;databasename=TopDB
#      username: sa
#      password: 123456
#      initialSize: 1
#      minIdle: 5
#      maxActive: 100
#      maxWait: 60000
#      testWhileIdle: true
#      testOnReturn: false
#      testOnBorrow: false
#      validationQuery: SELECT 1s
#      removeAbandoned: true
#      removeAbandonedTimeout: 1800
#      logAbandoned: true
#      filters: mergeStat
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 25200000



#spring:
#  datasource:
#    master:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#      username: root
#      password: root
#      type: com.zaxxer.hikari.HikariDataSource
#    cluster:
#    - key: slave1
#      url: jdbc:sqlserver://192.168.1.105;databasename=TopDB
#      username: sa
#      password: 123456
#      idle-timeout: 20000
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      type: com.zaxxer.hikari.HikariDataSource
#
#
#







spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#      url: jdbc:mysql://192.168.1.112:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: toot
#      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true



      redis:
        host: 127.0.0.1
        password:
        jedis:
          pool:
            min-idle: 0
            max-idle: 20
            #            max-wait: 5000
            max-active: 100

#多数据源的配置，需要引用renren-dynamic-datasource
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://192.168.1.105;databasename=TopDB
#      username: sa
#      password: 123456



dynamic:
  datasource:
    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.1.105;databasename=TopDB
      username: sa
      password: 123456






