#项目服务器配置
spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 1
        minIdle: 5
        maxActive: 100
        maxWait: 60000
        testWhileIdle: true
        testOnReturn: false
        testOnBorrow: false
        validationQuery: SELECT 1
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: mergeStat
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
    other:
      url: jdbc:sqlserver://192.168.1.105/TopDB?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: sa
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mircrosoft.sqlserver.SQLServerDriver
      initialSize: 1
        minIdle: 5
        maxActive: 100
        maxWait: 60000
        testWhileIdle: true
        testOnReturn: false
        testOnBorrow: false
        validationQuery: SELECT 1
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: mergeStat
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000

        redis:
          host: 127.0.0.1
          password:
          jedis:
            pool:
              min-idle: 0
              max-idle: 20
              #            max-wait: 5000
              max-active: 100






# 项目服务器配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_mj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    #    url: jdbc:mysql://47.110.159.133:3306/db_sdx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    #    password: "09161219"
#    password: root
#    initialSize: 1
#    minIdle: 5
#    maxActive: 100
#    maxWait: 60000
#    testWhileIdle: true
#    testOnReturn: false
#    testOnBorrow: false
#    validationQuery: SELECT 1
#    removeAbandoned: true
#    removeAbandonedTimeout: 1800
#    logAbandoned: true
#    filters: mergeStat
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 25200000
#
#    redis:
#      host: 127.0.0.1
#      password:
#      jedis:
#        pool:
#          min-idle: 0
#          max-idle: 20
#          #            max-wait: 5000
#          max-active: 100